name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy to Railway
        if: ${{ github.event_name == 'push' }}
        uses: bervProject/railway-deploy@main
        with:
          railway_token: 5b1f0b1c-f380-41d3-944a-4c7992f02f74
          service: "calculator"
        
